leancloud/javascript-sdk

dist/av.js
lib/browserify-wrapper/localstorage-browser.js
package.json

在 Safari 隐私模式下，localStorage.setItem() will throw.

[fix] replace localStorage with memoryStorage when unavailable.

---

lib/role.js

处理一种边缘情况：
```js
new AV.Role({
ACL:  new AV.ACL……
});
```
理论上用户可以这样设置  ACL 属性的。

Set ACL only when ACL is not exists yet.

---

lib/browserify-wrapper/upload-browser.js

In some versions of React Native, xhr.upload.addEventListener is not implemented.

[fix] Replace xhr.upload.addEventListener with onprogress.

---

lib/utils.js

`AV._request` is used in https://github.com/leancloud/javascript-sdk-installation-plugin. 需要访问 `/installation` route.

[feat] Support route 'installations'.

---

lib/object.js

`Object.new` cause SyntaxError in IE8.

[fix] Use square bracket notation.

---

lib/utils.js

原来的判断不够严谨，因为用户可能将 createdAt 设置为隐藏。
因此更安全的判断是认为返回的 json object value 的 keys 大于3个（className,__type, objectId)。

Fixed decoding pointer type.

---

lib/cloudfunction.js
lib/utils.js
test/cloud.js
test/test.html

添加 AV.Cloud.rpc 方法

---

gulpfile.babel.js
src/browserify-wrapper/ajax.js
test/user.js

[AV._request](https://github.com/leancloud/javascript-sdk/blob/master/lib/utils.js#L348) 中是期待错误情况下返回一个具有 responseText 属性的 xhr 对象的，但 ajax.js 里却返回了 `JSON.parse(responseText)`，这个错误会导致当请求出错时无法显示正确的错误提示。
之前的测试并没有覆盖这一点，因此我给 User.logIn 加了一个失败情况的测试来覆盖。

修正 ajax.js 在错误情况下返回值格式不正确的错误

---

package.json
src/browserify-wrapper/ajax-browser.js
src/cloudfunction.js
src/file.js
src/object.js
src/query.js
src/search.js
src/status.js
src/user.js
src/utils.js
test/cloud.js
test/user.js

https://github.com/leancloud/leanengine-node-sdk/issues/38

Disable current user

---

src/file.js
src/object.js
src/utils.js
test/object.js

- 支持 save 时传入 options.query
- 支持 save 时传入 options.fetchWhenSave
- 废弃 AV.Object#fetchWhenSave（仍可用）

implement AV.Object save options

---

src/browserify-wrapper/ajax.js

使用方法：`AV._ajax.userAgent = 'AV/js1.0.0-rc8; Node.js/v4.1.2';`
顺便又调整了一下默认的 User Agent 为符合 HTTP 标准的格式 `AV/js1.0.0-rc8; Node.js/v4.1.2`，因为目前这个 User Agent 还没被实际用到，所以这个修改不会产生影响。
#251

_ajax 暴露一个属性用于自定义 User Agent（Node.js 环境）

---

src/object.js
test/object.js

@wujun4code 
修复两个 Bug:
1. `object.fetch()` 会有 `read sessionToken from undefined` 的错误
2. include 选项不支持传递一个数组，这个行为和 `AV.Query` 以及其他 SDK 都不一致。这个问题在 rc8 存在，但因为这两天网络请求模块的修改，当前 master 的代码又不会有这个问题了（从 GET 请求改成了 POST 请求），但保险起见还是加了对数组的序列化处理。

fix(Object.fetch): options 默认为空对象、允许 include 选项为数组

---

src/cloudfunction.js
src/file.js
src/user.js

* AV.Cloud.rpc 方法也需支持 sessionToken 参数，之前是因为 PR 合并顺序的缘故落下了这个函数。
* disableCurrentUser 的情况下，AV.User.logOut 应该返回一个空的 Promise 而不是 return console.warn();
* disableCurrentUser 相关的警告只打印一次，以免日志打印过多；并用 console.trace() 打印调用栈，方便找到调用处。
https://github.com/leancloud/javascript-sdk/issues/251

有关 disable-current-user 的若干优化

---

src/av.js

#274 use browserify's UMD wrapper, which overrides predefined global AV.

fix(AV): use global AV if exists

---

src/promise.js
src/request.js

fix `A promise was resolved even though it had already been resolved.` error when `AV.init` called more then once.

fix: prevent getServerURLPromise from being resolved more then once

---

src/request.js

云引擎本地调试开启方法：`env DEBUG=leancloud:request lean up`。
* 调试的命名空间从 `request` 改为 `leancloud:request`，官方推荐用产品名加模块名来做命名空间。
* 添加一个计数器，否则在有并发请求的情况下无法区分哪个请求对应哪个响应（https://github.com/leancloud/javascript-sdk/issues/308 ）。我也想过在收到响应后再打印请求，但这样的话在请求超时的情况下就表现不是很好了，计数器还是最简单的解决方案。
* 响应也打印 headers，仅在 body 为空时打印 text.
这个功能主要还是为云引擎应用设计的，因为在浏览器里本来就可以用开发人员工具看到请求，这个 PR 合并后我会把这个说明补充到文档上，相信会给调试带来一些方便（尤其是我们向用户询问请求内容时）。

Improve http request log

---

package.json

RN start to support false value for package.browser package redirection.
Add "react-native" field to resort react-native dependency while packed for RN.
fix #342.

fix(package): support React Native v0.32

---

package.json
src/object.js
test/object.js
test/test.html

- 当调用 `AV.Object.extend` 只传一个参数时，直接返回已有的 class。
- 支持 ES6 的 extends 语法。由于 Class 声明没法自动注册，增加了 `AV.Object.register(Klass)` 方法用于注册。
close #331 close #337

fix AV.Object.extend SO error and support ES6 extends syntax

---

src/file.js
src/object.js
test/object.js

POTENTIALLY BREAKING:
before: object.get('id') //-> objectId
after: object.get('id') //-> id
before: object.set('objectId', 'xxx') // OK
after: object.set('objectId', 'xxx') // throw
https://github.com/leancloud/paas/issues/872

fix(Object): add reserved keys, remove id alias

---

package.json
src/request.js

- copy error.code and error.message when error is raised by a request
failure
- upgrade polyfill to handle request error correctly in weapp

fix: handle error raised by request failure

---

src/object.js
src/request.js
src/utils.js
test/hooks.js
test/test.js

之前我们使用了一种签名机制（ https://github.com/leancloud/uluru-platform/issues/2242 ）来验证客户端是否有权限（由 masterKey 签名）跳过 Hook 以及客户端是否希望跳过 Hook（是否有一个 __before 或者 __after 字段）；这个签名也用于客户端验证 Hook 调用是否是由可信的来源发起，不过这和该 PR 无关。在新的机制中，是否有权跳过 Hook 是由请求是否是用 masterKey 发起的来确定的，而是否希望跳过 Hook 是通过一个 `__ignore_hooks` 的属性。
在客户端实现上，之前是在 Node SDK 里通过这样的 hack 来实现的：
```
obj.set('__before', sign);
```
这实际上是相当于对对象做了一次修改，也就导致了 https://github.com/leancloud/cloud-code/issues/960 的这个 Bug，因此希望把跳过 Hook 的功能直接做到 JavaScript SDK 里来避免 hack.
完成「服务器验证客户端是否有权限跳过 Hook」和「客户端验证 Hook 调用是否是由可信的来源发起的」两项工作；新的机制（ https://github.com/leancloud/uluru-platform/issues/2384 ）将会引入一个 Hook Key 的机制。
目前只实现了一个原型版本，还有很多问题需要考虑：

AVObject#ignoreHook, disableBeforeHook, disableAfterHook

---

src/file.js
src/uploader/qiniu.js
src/utils/parse-base64-browser.js

close #410 
并且由于客户端不再知道 mimeType，SDK 不再在 metaData 中加入 mimeType，close #236 
因此，这是个 breaking change。

refactor(File): remove ext-mimeType map as it's done by server

---

src/file.js

if name not set and the file is large, qiniu will respond with "invalid multipart format: multipart: message too large" error.
see https://leanticket.cn/t/leancloud/3547

fix(File): add default blob.name

---

package.json

https://forum.leancloud.cn/t/cannot-assign-to-read-only-property-localstorage-of-object-window/12967/

fix(weapp): prevent throwing when 6to5 transform not enabled

---

src/av.js
src/file.js
src/geopoint.js
src/insight.js
src/object.js
src/op.js
src/query.js
src/relation.js
src/search.js
src/status.js
test/file.js
test/object.js

背景：
- `AV.Object#toJSON`，`AV.Object#_toFullJSON`方法返回的 JSON 中是不包含 included Pointers 的内容的，需要用户自行遍历处理。
- `AV._decode` 调用的是 `AV.Object#_toFullJSON`，因为上面这个问题，所以目前没有办法对一个 AV.Object 进行完整的序列化与反序列化。此外这个方法理应是 internal 的。
为了解决这两个问题，在新版中，`AV.Object#toJSON` 的定位是输出对象的有效信息，可以传给视图层直接消费。新增 `AV.Object#toFullJSON`，定位为序列化方法，输出包括类型信息在内的所有信息，可以通过新增的 `AV.parseJSON` 方法（alias `AV._decode`）反序列化，可以用来实现对象的持久化。
在这个 PR 里，为了保持兼容性，保留了 `AV.Object#_toFullJSON` 及其默认的行为，但这个方法其实的作用是 `_toJSON` ，并且可以通过两个参数控制输出 JSON 的行为。
- `seenObjects`: if falesy，将 Pointer 输出 Pointer 类型，否则尽可能贪心的输出 included 的 Pointer 内容（直到遇到循环依赖）。
- `full`: 控制是否输出 `__type` 与 `className` 的 meta 信息。
新设计 (v2) 中的 API 是组合这两个参数的结果：
| |full: false|full: true|
----|----|----
seenObjects: fales|`#toJSON`(v1)|`#_toFullJSON` (default)
seenObjects: …

feat(Object): make toJSON result contains included pointers

---

src/query.js

https://forum.leancloud.cn/t/to-create-a-role-without-acl/14841

fix(Role): stop complaint about defaultACL when query Roles

---

src/uploader/s3.js
webpack/common.js

之前的配置导致 stream 在非 node 中被替换成 `{}`

fix(File): check stream in node.js only

---

src/user.js

https://forum.leancloud.cn/t/bug/15205
微信的文档没有关于 fail 参数的说明，也不知道什么时候会进入 fail，只能希望是这里的问题。

fix(Weapp): handle failed wx.login

---

src/object.js
src/utils/index.js
storage.d.ts
test/object.js

在 AV.Object 子类上增加一个便捷属性，来创建此类的 AV.Query 实例。

feat: add AV.Object.query

---

src/object.js
src/user.js
src/utils/index.js
test/user.js

also refactor `Object#_applyOpSet` and `Object#set` to support operations like `object.set('a.b', 1)`;

fix(user): reimplement #dissociate with unset op

---

storage.d.ts

为 PushData 增加 prod 属性。
ts 定义中限制了 prod 的取值，只能为 dev 或 prod。

fix(ts): add prod to PushData.

---

src/object.js

`this.get('createdAt')` itself evaluates to
`this.createdAt`,
thus `this.createdAt || this.get('createdAt')` is unnecessary.
The same applies to `getUpdatedAt`.

refactor(AVObject): simplify get Created/UpdatedAt

---

storage.d.ts

Thanks to secoinfo for reporting this.

fix(login): typo in type definitions

---

core.js
live-query-core.js
live-query.js
package.json
src/captcha.js
src/entry/use-adapters.js
src/init.js
src/request.js
webpack/common.js

这个 PR 做了下面这些改动：
- 直接用 Babel 转译得到的 dist/cjs 改为 dist/node，将其视为 Node.js 版本（其中包含了部分只有 Node.js 中能运行的逻辑）。
- 修改代码中 Node.js-only 部分的判定条件，只在 Node.js 版本中出现。
- `./core` 指向 `dist/av-core.js`。`dist/av-core.js` 是真正的 platform 无关 build。
- 如果 React Native 直接引入 "leancloud-storage"（而非 core），将其 redirect 到 core.js。
- （顺带）将浏览器与微信小程序的入口改成未 minify 的版本。
能解决：
- 部分不支持改写 User-Agent header 的 platform 无法使用 core 的问题
- React Native 引用了 `leancloud-storage/core` 但是提示没有 stream 模块的问题（Node.js-only 逻辑）

fix: 移除 core 中 Node.js 相关的逻辑

---

changelog.md
src/file.js

Detail: leancloud/rfcs#1091
和之前使用上有一点差异：直接创建 Object 时，即便用户不提供 mime_type ，也不会自动根据 name 生成 mime_type 。

refactor: create Object directly when upload external file

---

changelog.md
src/friendship.js
src/index.js
src/user.js
storage.d.ts

原本未计划在 4.x 版本实现「好友」，想了想还是实现一下吧，毕竟 4.x 在 5.0 发布后的很长一段时间内，仍会是主要使用版本。
之前[未完成的实现](https://github.com/leancloud/javascript-sdk/tree/feat/friendship)，放在一起作参考。与其相比：
- 没有重命名 `FriendShipQuery `
- 没有实现特化的 `FriendshipRequest ` Object
---
> 参考：https://leancloud.atlassian.net/wiki/spaces/PROD/pages/1105854465
当前登录用户申请成为 Tom 的好友：
```js
AV.Friendship.request("tom's objectId")
.then(() => {
console.log('好友请求发送成功');
})
.catch((error) => {
console.error('好友请求发送失败', error);
});
```
申请的同时添加属性：
> 这里模仿了 AV.User#follow 的使用风格
```js
AV.Friendship.request({
friend: "tom's objectId",
attributes: {
group: ['husband'],
},
});
```
如果 Tom 不在线，上线后要查询谁正在添加自己为好友：
```js
const query = new AV.Query('_FriendshipRequest');
query.equalTo('friend', AV.User.current());
query.equalTo('status', 'pending'); …
```

feat: friendship

---

src/object.js
src/query.js
storage.d.ts

加了两个功能：
- AV.saveAll 支持 fetchWhenSave
之前如果 AV.Object 持有未保存的 AV.Object 时会使用 batch 一起保存，这时候 fetchWhenSave 是不生效的，等于还修了个 bug :ease:
- AV.Query#findAndCount
手动测试了一下。

feat: findAndCount

---

storage.d.ts

The return type of `getObjectId` should be `string`, not `String`.

fix(type): fix return type of getObjectId

---

storage.d.ts

前景提要：
https://github.com/leancloud/ticket/pull/609/files#diff-dec40c8cf82954eb426791bbfd0c151ce050d78f836fabb5cf4afdaccd1e2566L177
#666 
#324
尝试了一下让 AV.Error 继承 Error，发现有难度。一是目前的 AV.Error 支持直接（不用 new 关键字）调用，如果用  ES6 class 那么就是个 breaking change 了。二是就算用 ES6 的继承，babel 6 对 Error 继承也有 bug： https://github.com/babel/babel/issues/8385 （这个版本暂时不想升 babel 7）。
所以最终改了定义文件，避免用户写出 `error instanceof AV.Error` 这样的 type guard。如果用户需要区分出 AV.Error，单独写一个 isAVError 通过判断 error.code 类型作为 type guard。

fix(type): export AV.Error as an interface

---

src/error.js
storage.d.ts
test/error.js

还是没用 ES6 的继承语法，是为了能同时当作 factory / 构造函数使用。
ES6 class + Proxy 也能实现想要的效果，但 Proxy 没法 polyfill，就放弃了。

feat: make AV.Error constructible and inheritable

---

src/status.js
storage.d.ts

补充 AV.Status 相关的类型定义。用文档里的示例代码测了下没有类型错误。

feat(AV.Status): type definition

---

src/user.js
storage.d.ts

为了使 _User 表的 create 权限为 0 Users 时可以通过 masterKey 创建用户，需要将 useMasterKey 透传到 Object.prototype.save 里

feat: make authOptions available in loginWithAuthData

---

src/utils/index.js

某些 iOS 设备**可能**不支持使用 `yyyy-MM-ddTHH:mm:ssZ` 格式的字符串创建 Date。
微信开发者工具在新版中[加入了警告](https://developers.weixin.qq.com/community/minihome/doc/00080c6f244718053550067736b401)，每次用上述格式调用 Date 构造函数时就会在控制台打印一条日志，影响开发时的体验。
由于不方便在 adapters 中修改 AV 上面的方法，索性直接改写 AV._parseDate，也同时支持了 react-native 等平台。
```
$ node benchmark.js '2020-01-02T03:04:05.678Z' 10000000
new Date(dateString): 4.375s
new Date(Date.parse(dateString)): 4.687s
```

feat: adapt iOS date string format
