lib/object.js
lib/promise.js
test/promise.js
test/test.html

主要是为了兼容 Promise/A+ 的 API，增加
* `AV.Promise.all`
* `AV.Promise.race`
* `AV.Promise#catch`
* `new AV.Promise(fn)`
@sunchanglong  @aisk @wangxiao 帮忙看下

Fixed #34. Added AV.Promise#catch,AV.Promise.race etc.

---

lib/query.js

Declare obj in strict mode.

---

lib/file.js

修复 AV.File 的文档错误，没有生成单独 class 文档。

Fixed AV.File doc

---

lib/query.js

修复一个排序的bug

---

lib/file.js
test/file_blob.html

* AV.File构造选项
```
var newFile = new AV.File('fileName', {blob: someBlob});
```
* 增加`save`方法的参数，提供上传进度回调
```
var progressCb = function(e) {
console.debug(e.loaded, e.total);
};
newFile.save({onProgress: progressCb}, null);
```
* 增加测试

Construct AV.FIle with blob and upload directly to Qiniu

---

.travis.yml
README.md
package.json

[build] Add travis config.

---

dist/av-core.js
dist/av.js
gulpfile.js
lib/role.js
test/role.js
test/test.html

[feature] Use the default acl for AV.Role if absent.

---

lib/promise.js
lib/utils.js
test/promise.js

[fix] AV._request not working in React Native.

---

lib/search.js

为搜索  API 增加 hasMore 和 reset 函数，前者用于查询是否到达末尾，后者用于重设当前 query 状态，可以开始一次新查询。

Adds hasMore and reset for AV.SearchQuery.

---

lib/browserify-wrapper/xmlhttprequest.js
package.json

Close #132.
https://github.com/leancloud/cloud-code/issues/295

[feat] Enable keep-alive for node http[s] client.

---

lib/user.js

https://ticket.leancloud.cn/tickets/9045

[fix] AV.User#fetch does not support fetch options.

---

lib/query.js
lib/user.js
test/query.js
test/user.js

fix issue that callbacks not get called in some conditions.

fix(query): throw error instead of return rejected Promise.

---

package.json

fix(browserify): 修复了错误的 package.browser 引起的打包异常

---

src/browserify-wrapper/upload-browser.js

fix(File): use qiniu https upload endpoint

---

.editorconfig
.travis.yml
demo/index.html
gulpfile.babel.js
src/av.js
src/browserify-wrapper/ajax-browser.js
src/browserify-wrapper/ajax.js
src/cache.js
src/utils.js
test/cache.js
test/test.html

feat: app router

---

src/file.js
test/file.js

us: data = { blob: Buffer }
e1: data = Buffer

fix(File): add support to following use cases

---

src/object.js
test/object.js

@wujun4code 
大概是我当时不太清醒 ... 不过的确单元测试覆盖有点低。

fix(Object.fetch): fetchOptions.include.join is not a function

---

src/file.js
test/file.js

fix(File): parse bytes array to base64 then treat the source as base64

---

demo/index.html

Mac用户表示打开是乱码啊。增加了字符集头。我不是前端开发，不知道这个fix是否合理，希望改善这个问题

Demo的字符集错误

---

src/error.js
src/object.js
src/utils.js
test/object.js

Ensure the second param of AV.Object#add, AV.Object#addUnique,
AV.Object#remove to be an Array.

fix(Object): add support to object.add(key, array)

---

src/object.js
src/request.js
test/object.js

feat(Object): add AV.Object.fetchAll

---

src/request.js

两点改动：
- app-router 如果返回 4xx，则 reject 后续的 request promises，其他异常情况下直接按照默认的 server 请求
- 最里层（createApiUrl）如果 `AV._config.APIServerURL` 不存在，使用 `API_HOST.cn`

fix: pass app-router error to request

---

src/file.js
src/object.js
test/object.js
test/user.js

详见 test/object.js 增加的  test case.

fix(Object): stop attempting to get attributes from this

---

src/file.js
src/query.js
test/query.js
test/test.js

fix AV.File can not be query.

---

src/query.js

fix(Query): correct addDesceding to return this

---

package.json
src/uploader/cos.js
src/uploader/qiniu-browser.js
src/uploader/s3.js

	fix(File): add progress event listener before req.end

---

src/object.js
src/query.js
test/object.js
test/user.js

fix(Query): AV.Query#get use fetch now

---

.travis.yml
src/query.js
test/query.js

feat(Query): throw Errors when undefined is specified as key/value

---

src/request.js

fix: prioritize options.useMasterKey over AV._useMasterKey

---

src/request.js

fix(Insight): skip signing keys when sending Insight job requests

---

package.json

https://github.com/leancloud/weapp-polyfill/commit/ca6dffd61ef6a0475f826112b256aa53bd01dcf1

chore(File): support weapp

---

src/user.js
test/user.js

https://github.com/leancloud/paas/issues/863

feat(User): add #isAuthenticated, deprecate #authenticated

---

src/request.js

fix: stringify headers to prevent an Expection in RN

---

src/status.js

https://forum.leancloud.cn/t/av-status-sendprivatestatus/12119

fix(status): fix undefined AV

---

package.json
src/promise.js
webpack/common.js

reduce bundle size from 135 KB to 125KB 🎉

refactor: replace rsvp with es6-promise

---

src/object.js
test/object.js

feat(Object): allow user to specify the name when registering class

---

src/av.js
src/cloudfunction.js
src/insight.js
src/object.js
src/op.js
src/status.js
test/av.js
test/index.js
test/object.js
test/test.html

and prevent Object.set() from muting value param, fix 392
change `AV._decode(key, value)` to `AV._decode(value[, key])`， leanengine-sdk 也需要更新。

fix: purify AV._decode/_encode

---

src/request.js
test/query.js

fix: convert to batch API when URI might be too long

---

package.json
src/av.js
src/file.js
src/init.js
src/request.js
src/ua/index.js
webpack/common.js

以及移除了 `AV._config.isNode`，换成条件编译。

feat: allow to auto init AV with env variables in Node.js

---

src/av.js
src/file.js
test/av.js
test/query.js

also this makes File compatible with Query, close #411

fix(File): decode Files properly

---

package.json

chore(package): upgrade superagent

---

src/uploader/qiniu.js

fix(File): file.has -> file.get

---

src/request.js
src/user.js
test/user.js

https://github.com/leancloud/paas/issues/871
以及去掉了 checkRouter，似乎并没有什么用。

feat(User): #refreshSessionToken

---

src/utils.js
test/file.js

backport #438 but without toJSON refactoring.

fix(File): add missing fields to File#toJSON

---

src/av.js
src/file.js
src/object.js
test/file.js

https://forum.leancloud.cn/t/rpc/13052
also move File#toJSON logic from AV._decode to File

fix(File): add missing data for #toJSON

---

src/query.js
src/request.js
test/query.js

fix https://forum.leancloud.cn/t/js-sdk-v2-0-1-batch/13109

fix(Query): correct batch format and add error handler

---

src/query.js
test/query.js

https://github.com/leancloud/paas/issues/885

feat(Query): #scan

---

src/file.js
src/utils/index.js

https://github.com/leancloud/uluru-platform/issues/3201

feat(File): support file callback

---

src/status.js
test/status.js

https://github.com/leancloud/paas/issues/870

feat(Status): 重置未读消息数

---

src/query.js
src/user.js
test/user.js

	fix(User): refreshSessionToken also refresh cache

---

src/file.js

https://forum.leancloud.cn/t/react-native-android-av-file-ios/13837
去掉本地的 mimeType guessing 之后，对 data 的处理需要移到 fileToken 获取到 mimeType 之后进行。

fix(File): parse file data after fileToken

---

src/request.js

be73b2856e2992d5e76b0a3315f30e3d555cbfdc
之前 pick 的时候不知道在想什么。

fix(Insight): add missing param, fix #377 again

---

src/push.js

Related ticket: https://leanticket.cn/t/leancloud/4430

doc: update AV.Push.send API doc

---

src/role.js
storage.d.ts
test/role.js
test/user.js

https://leanticket.cn/t/leancloud/4149
This is a BREAKING CHANGE.

feat(Role): remove defaultACL

---

src/utils/localstorage-browser.js

fixed https://forum.leancloud.cn/t/iphone-22/14316

fix(localStorage): use memory storage as fallback in safari private mode

---

src/file.js
src/object.js
src/query.js
src/utils/index.js
test/acl.js
test/query.js

- add `Query#includeACL`
- add `fetchOptions.includeACL` for `Object#fetch` 
https://github.com/leancloud/paas/issues/912

feat(ACL): add includeACL flag for Query and fetching

---

src/user.js
storage.d.ts
test/status.js

https://github.com/leancloud/paas/issues/763

feat(Status): Follower/Followee support attributes

---

package.json
src/user.js
webpack/rn.js

3.0 React Native compatibility fix

---

src/status.js

prevent currentUser warning when used with AuthOptions in node.

fix(Status): prioritize AuthOptions over currentUser

---

src/file.js

File is extended from Blob.
https://leanticket.cn/tickets/13372

fix(File): accept Blob

---

src/push.js
storage.d.ts

相关工单： https://leanticket.cn/tickets/13552

fix: AV.Push.send type interface

---

src/request.js
test/user.js

feat(Error): add request details in error.message

---

src/user.js

fix https://leanticket.cn/tickets/13721

fix(User): put sessionToken in headers for User.become

---

src/object.js
src/op.js
storage.d.ts
test/object.js

https://github.com/leancloud/paas/issues/811

feat: add bit related operations on AV.Object

---

src/file.js
src/uploader/cos.js
src/uploader/qiniu.js
src/uploader/s3.js
storage.d.ts

https://github.com/leancloud/paas/issues/960

feat(File): add #setUploadHeader

---

src/uploader/qiniu.js

https://github.com/leancloud/paas/issues/962

fix(File): use dynamic qiniu up url

---

src/query.js
src/status.js
test/status.js

https://leanticket.cn/tickets/14098

fix(inboxQuery): use super _createRequest to prevent URI too long

---

src/object.js
test/object.js

https://leanticket.cn/tickets/14080

fix(Object): use pure _dirty to prevent unnecessary saves with circular references

---

src/object.js
test/hooks.js
test/object.js

`AV.Object#fetchAll`，`AV.Object#saveAll`， `AV.Object#destroyAll` 遇到失败时，抛出的 error 对象增加 results 属性，类型为 `Array<AV.Object|Error>`
close #96
https://leanticket.cn/tickets/14146

feat(Object): add batch error.results

---

src/query.js
storage.d.ts

fix(ts): allow followerQuery & followeeQuery to support subclass of AV.User

---

storage.d.ts

feat(ts):more accurate GeoPoint constructor typing

---

src/live-query.js
src/object.js
src/push.js
src/query.js
src/search.js
src/status.js
storage.d.ts
test/query.js

BREAKING CHANGE: The original #toJSON is renamed to #_getParams

feat(query): add .fromJSON and a new #toJSON

---

storage.d.ts

feat(typing): Cloud.useMasterKey

---

src/user.js
test/user.js

fix(user): update sessionToken after call updatePassword

---

src/cloudfunction.js
src/index.js
src/user.js
storage.d.ts

相关 [rfc](https://github.com/leancloud/rfcs/issues/1081) 及 [工单](https://leanticket.cn/tickets/35931)。
已手动测试通过，因为涉及真实手机号码，就不加单测了。

feat: 支持修改手机号前先进行验证

---

src/user.js

写 jsdoc 时疏忽了，`authInfo` 应该是可选参数。

docs: make authInfo optionally

---

storage.d.ts

fix(ts): add descending in BaseQuery

---

package-lock.json
src/search.js

feat: SearchQuery#find accept authOptions

---

src/file.js
src/uploader/qiniu.js
src/utils/parse-base64.js

See: leancloud/rfcs#1085
顺手改了下 Buffer 的构建方式。

refactor(file): use the key generated by the server

---

src/file.js
src/object.js

feat: verify objectId when create object without data

---

recordings/AV-Cloud_4059047921/-rpc_2399869033/send-AVObject_366179365/recording.har
recordings/AV-Cloud_4059047921/-rpc_2399869033/send-bare-AVObject_2666081587/recording.har
src/object.js

相关工单: https://www.leanticket.cn/tickets/37015
不清楚之前为什么要加上这个限制，放开后会有什么影响吗？

feat(object): remove restriction of saveAll

---

src/file.js
src/object.js

很奇怪，我的webpackage没法很好的转化 _(Array).each这种写法。  反正这种写法也比较过时所以改了一下。

修改_(Array).each 的写法

---

src/uploader/cos.js
src/uploader/qiniu.js
src/uploader/s3.js

fix: set URL attribute after upload succeed

---

src/file.js
src/object.js
test/file.js
test/object.js

fix: throws when fetching object without id

---

src/uploader/qiniu.js
src/utils/btoa.js

Close #649
目前设置为：大于 64MB 的文件使用分片上传机制，每个分片 16MB 。这是我随便设置的，不合适可以改 👀

feat(qiniu): shard upload

---

src/init.js

See:
https://www.leanticket.cn/tickets/37913
https://xindong.slack.com/archives/C01RY599GNB/p1623145999002100
结论：还原 3.x 时的行为。

refactor: assign AV._config.production directly

---

src/uploader/qiniu.js

https://xindong.slack.com/archives/C01HZ8BS7PT/p1623228914149200?thread_ts=1623228781.149100&cid=C01HZ8BS7PT
upload 后忘记设置 id / url 并返回文件了，导致返回结果是 ajax 函数调用的结果。

fix: return file object after uploaded

---

src/uploader/qiniu.js

fix: make jsdoc happy

---

src/object.js

fix: re-save files

---

src/query.js
test/query.js

to comfort the iterator protocol

fix(scan): return the last item with done:false

---

src/query.js
storage.d.ts

See: https://forum.leancloud.cn/t/js-sdk-v4-12-0-query-d-ts-sizeequalto/25001

fix: add type definition of AV.Query#sizeEqualTo

---

src/error.js
src/query.js
src/request.js
storage.d.ts

background: https://github.com/leancloud/ticket/pull/609/files#diff-dec40c8cf82954eb426791bbfd0c151ce050d78f836fabb5cf4afdaccd1e2566L177
一行代码踩两个坑：
1. AV.ErrorCode 是不存在的
2. 这个 error 不是 AV.Error

Revise AVError 

---

src/friendship.js

用户反馈在使用异步 storage 的平台上无法发送好友请求，因为 AV.Friendship.request 内部使用的是 AV.User.current 这个方法。
看了下 [API](https://leancloud.cn/docs/leanstorage_friendship_guide.html#hash509259984) 的定义，发现加好友的请求不光需要发起者的 sessionToken，还需要 objectId。由于 AV.Friendship.request 是支持设置 AuthOptions 的，所以不能简单替换为 AV.User.currentAsync。
所以加了个工具函数，从 authOptions.sessionToken、authOptions.user 和 AV.User.currentAsync() 这三个地方拿已登录的用户。
AV.Friendship.acceptRequest 和 AV.Friendship.declineRequest 也通过 AV.User.currentAsync 检测是否有已登录用户。

feat(friendship): prefer AV.User.currentAsync
